#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#pylint:disable=W0301
#  
#  Copyright 2018- William Martinez Bas <metfar@gmail.com>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#
"""sumX help adapter.

``help.md`` is the canonical editable source. ``help.helpdb`` is generated by
SumDoc and is the runtime representation consumed here, keeping sumX and
sumTUI independent of the conversion toolkit at runtime.
""";
from importlib.resources import files;

from sumtui.helpdb import HelpCorpus, HelpTopic;


def _load_corpus():
    text = files("sumx").joinpath("help.helpdb").read_text(encoding="utf-8");
    return HelpCorpus.from_helpdb(text);


CORPUS = _load_corpus();
_TOPICS = list(CORPUS.topics);
TOPICS = {topic.name.upper(): topic for topic in _TOPICS};
ALIASES = dict(CORPUS._aliases);


def topic_names():
    return CORPUS.topic_names();


def find_topic(name):
    return CORPUS.find_topic(name);


def index_markdown():
    return CORPUS.index_markdown();
