#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Generated by sumX. This file intentionally depends on the sumX runtime.
# The generated form stays readable so students can inspect the translation.

from sumx.compiler_support import GeneratedProgram;

program = GeneratedProgram(source_name='examples/conditionals.prg');
program.interpreter.runtime.set_line_continuation('BACKSLASH');
program.interpreter.runtime.set_ampersand_comment(False);

# sumX line 2: a = 5
program.statement('a = 5', source_line=2);
# sumX line 3: ready = ON
program.statement('ready = ON', source_line=3);
# sumX line 4: enabled = OFF
program.statement('enabled = OFF', source_line=4);
# sumX line 6: IF a == 5 THEN PRINT "single line IF"
if program.condition('a == 5', source_line=6):
    # sumX line 6: PRINT "single line IF"
    program.statement('PRINT "single line IF"', source_line=6);
# sumX line 8: IF ready && ~enabled THEN
if program.condition('ready && ~enabled', source_line=8):
    # sumX line 9: PRINT "block line 1"
    program.statement('PRINT "block line 1"', source_line=9);
    # sumX line 10: PRINT "block line 2"
    program.statement('PRINT "block line 2"', source_line=10);
else:
    # sumX line 12: PRINT "not ready"
    program.statement('PRINT "not ready"', source_line=12);
# sumX line 15: PRINT "XOR:"
program.statement('PRINT "XOR:"', source_line=15);
# sumX line 16: ? ready ^^ enabled
program.statement('? ready ^^ enabled', source_line=16);

raise SystemExit(program.finish());
