# PICTURE and TRANSFORM share the same formatting engine.
SET FIELD_WRAP_OVERFLOW OFF;
PRINT 1250.50 PICTURE "$999,999.99";
PRINT TRANSFORM(450.00, "**,***.99");
PRINT TRANSFORM("usuario12", "@! NNNNNNNN");
SET FIELD_WRAP_OVERFLOW ON;
PRINT TRANSFORM("usuario12", "@! NNNNNNNN");
